-- +goose Up
-- +goose StatementBegin

-- +goose StatementEnd

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CUSTOMERS (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    FULLNAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    PASSWORD VARCHAR,
    SALT VARCHAR,
    STATUS VARCHAR,
    RANK VARCHAR,
    BONUS NUMERIC(12,2) NULL DEFAULT 0,
    CREATED_BY UUID,
    CREATED_AT timestamp with time zone DEFAULT now() NOT NULL,
    UPDATED_AT timestamp with time zone DEFAULT now() NOT NULL,
    DELETED_AT timestamp with time zone,
    IS_DELETED boolean DEFAULT false
);

CREATE INDEX IDX_CUSTOMERS_ID ON CUSTOMERS(ID);
CREATE INDEX IDX_CUSTOMERS_CREATED_AT ON CUSTOMERS(CREATED_AT);
-- CREATE UNIQUE INDEX IDX_CUSTOMERS_PHONE ON CUSTOMERS(PHONE_NUMBER);
-- CREATE UNIQUE INDEX IDX_CUSTOMERS_STORE_NAME ON CUSTOMERS(STORE_NAME);

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS CUSTOMERS;
-- +goose StatementEnd
