version: '3'

services:
  postgres:
    container_name: postgre_webinar
    working_dir: /usr/app
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data
    image: 'postgres:9.6.10-alpine'
    environment:
      POSTGRES_USER: webinar
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB : webinar
      PG_VERSION: '9.6.10-alpine'
    ports:
      - "5432:5432"
    networks:
      - web
networks:
  web:
    driver: bridge